---
appStore:
- id: '982091927'
  name: セブン−イレブン マルチコピー
googlePlay:
- id: jp.co.fujixerox.mcopy
  name: セブン−イレブン マルチコピー
mail:
  IsEnabled: false
  host: localhost
  port: 25
  fromAddress: ''
  toAddresses:
  - ''
excel:
  outDir: 
sqlite:
  dbPath: 
